[project]
name = "stacks-tipjar"
description = "Creator monetization platform on Stacks"
authors = ["serayd61"]
telemetry = false
cache_dir = ".cache"
requirements = []

[contracts.tipjar]
path = "contracts/tipjar.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]


